version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:3.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api-gateway-service:
    build: ./api-gateway-service
    command: npm run serve
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway-service/src:/api-gateway-service/src

  authentication-service:
    build: ./authentication-service
    command: npm run serve
    depends_on:
      - mongodb
      - api-gateway-service
    ports:
      - "3001:3000"
    volumes:
      - ./authentication-service/src:/authentication-service/src

  lobby-service:
    build: ./lobby-service
    command: npm run serve
    depends_on:
      - zookeeper
      - kafka
      - mongodb
      - api-gateway-service
    ports:
      - "3002:3000"
    volumes:
      - ./lobby-service/src:/lobby-service/src

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
